/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets.index'
import { Route as AuthenticatedTicketsNewRouteImport } from './routes/_authenticated/tickets.new'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated/tickets.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTrashRouteImport } from './routes/_authenticated/admin.trash'
import { Route as AuthenticatedAdminRankingRouteImport } from './routes/_authenticated/admin.ranking'
import { Route as AuthenticatedAdminExecutiveRouteImport } from './routes/_authenticated/admin.executive'
import { Route as AuthenticatedAdminCompareRouteImport } from './routes/_authenticated/admin.compare'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminTechniciansIndexRouteImport } from './routes/_authenticated/admin.technicians.index'
import { Route as AuthenticatedTicketsIdRateRouteImport } from './routes/_authenticated/tickets.$id.rate'
import { Route as AuthenticatedAdminTicketsIdRouteImport } from './routes/_authenticated/admin.tickets.$id'
import { Route as AuthenticatedAdminTechniciansIdRouteImport } from './routes/_authenticated/admin.technicians.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketsNewRoute = AuthenticatedTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTrashRoute = AuthenticatedAdminTrashRouteImport.update({
  id: '/admin/trash',
  path: '/admin/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRankingRoute =
  AuthenticatedAdminRankingRouteImport.update({
    id: '/admin/ranking',
    path: '/admin/ranking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExecutiveRoute =
  AuthenticatedAdminExecutiveRouteImport.update({
    id: '/admin/executive',
    path: '/admin/executive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompareRoute =
  AuthenticatedAdminCompareRouteImport.update({
    id: '/admin/compare',
    path: '/admin/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/admin/activity',
    path: '/admin/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTechniciansIndexRoute =
  AuthenticatedAdminTechniciansIndexRouteImport.update({
    id: '/admin/technicians/',
    path: '/admin/technicians/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketsIdRateRoute =
  AuthenticatedTicketsIdRateRouteImport.update({
    id: '/rate',
    path: '/rate',
    getParentRoute: () => AuthenticatedTicketsIdRoute,
  } as any)
const AuthenticatedAdminTicketsIdRoute =
  AuthenticatedAdminTicketsIdRouteImport.update({
    id: '/admin/tickets/$id',
    path: '/admin/tickets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTechniciansIdRoute =
  AuthenticatedAdminTechniciansIdRouteImport.update({
    id: '/admin/technicians/$id',
    path: '/admin/technicians/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/compare': typeof AuthenticatedAdminCompareRoute
  '/admin/executive': typeof AuthenticatedAdminExecutiveRoute
  '/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRouteWithChildren
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/admin/technicians/$id': typeof AuthenticatedAdminTechniciansIdRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/tickets/$id/rate': typeof AuthenticatedTicketsIdRateRoute
  '/admin/technicians/': typeof AuthenticatedAdminTechniciansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/compare': typeof AuthenticatedAdminCompareRoute
  '/admin/executive': typeof AuthenticatedAdminExecutiveRoute
  '/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRouteWithChildren
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/admin/technicians/$id': typeof AuthenticatedAdminTechniciansIdRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/tickets/$id/rate': typeof AuthenticatedTicketsIdRateRoute
  '/admin/technicians': typeof AuthenticatedAdminTechniciansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/compare': typeof AuthenticatedAdminCompareRoute
  '/_authenticated/admin/executive': typeof AuthenticatedAdminExecutiveRoute
  '/_authenticated/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/_authenticated/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRouteWithChildren
  '/_authenticated/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/admin/technicians/$id': typeof AuthenticatedAdminTechniciansIdRoute
  '/_authenticated/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/_authenticated/tickets/$id/rate': typeof AuthenticatedTicketsIdRateRoute
  '/_authenticated/admin/technicians/': typeof AuthenticatedAdminTechniciansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/notifications'
    | '/stats'
    | '/admin/activity'
    | '/admin/compare'
    | '/admin/executive'
    | '/admin/ranking'
    | '/admin/trash'
    | '/admin/users'
    | '/tickets/$id'
    | '/tickets/new'
    | '/tickets/'
    | '/admin/technicians/$id'
    | '/admin/tickets/$id'
    | '/tickets/$id/rate'
    | '/admin/technicians/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/notifications'
    | '/stats'
    | '/admin/activity'
    | '/admin/compare'
    | '/admin/executive'
    | '/admin/ranking'
    | '/admin/trash'
    | '/admin/users'
    | '/tickets/$id'
    | '/tickets/new'
    | '/tickets'
    | '/admin/technicians/$id'
    | '/admin/tickets/$id'
    | '/tickets/$id/rate'
    | '/admin/technicians'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/stats'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/compare'
    | '/_authenticated/admin/executive'
    | '/_authenticated/admin/ranking'
    | '/_authenticated/admin/trash'
    | '/_authenticated/admin/users'
    | '/_authenticated/tickets/$id'
    | '/_authenticated/tickets/new'
    | '/_authenticated/tickets/'
    | '/_authenticated/admin/technicians/$id'
    | '/_authenticated/admin/tickets/$id'
    | '/_authenticated/tickets/$id/rate'
    | '/_authenticated/admin/technicians/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/new': {
      id: '/_authenticated/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AuthenticatedTicketsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/trash': {
      id: '/_authenticated/admin/trash'
      path: '/admin/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AuthenticatedAdminTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ranking': {
      id: '/_authenticated/admin/ranking'
      path: '/admin/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AuthenticatedAdminRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/executive': {
      id: '/_authenticated/admin/executive'
      path: '/admin/executive'
      fullPath: '/admin/executive'
      preLoaderRoute: typeof AuthenticatedAdminExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compare': {
      id: '/_authenticated/admin/compare'
      path: '/admin/compare'
      fullPath: '/admin/compare'
      preLoaderRoute: typeof AuthenticatedAdminCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/technicians/': {
      id: '/_authenticated/admin/technicians/'
      path: '/admin/technicians'
      fullPath: '/admin/technicians/'
      preLoaderRoute: typeof AuthenticatedAdminTechniciansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/$id/rate': {
      id: '/_authenticated/tickets/$id/rate'
      path: '/rate'
      fullPath: '/tickets/$id/rate'
      preLoaderRoute: typeof AuthenticatedTicketsIdRateRouteImport
      parentRoute: typeof AuthenticatedTicketsIdRoute
    }
    '/_authenticated/admin/tickets/$id': {
      id: '/_authenticated/admin/tickets/$id'
      path: '/admin/tickets/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AuthenticatedAdminTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/technicians/$id': {
      id: '/_authenticated/admin/technicians/$id'
      path: '/admin/technicians/$id'
      fullPath: '/admin/technicians/$id'
      preLoaderRoute: typeof AuthenticatedAdminTechniciansIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTicketsIdRouteChildren {
  AuthenticatedTicketsIdRateRoute: typeof AuthenticatedTicketsIdRateRoute
}

const AuthenticatedTicketsIdRouteChildren: AuthenticatedTicketsIdRouteChildren =
  {
    AuthenticatedTicketsIdRateRoute: AuthenticatedTicketsIdRateRoute,
  }

const AuthenticatedTicketsIdRouteWithChildren =
  AuthenticatedTicketsIdRoute._addFileChildren(
    AuthenticatedTicketsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminCompareRoute: typeof AuthenticatedAdminCompareRoute
  AuthenticatedAdminExecutiveRoute: typeof AuthenticatedAdminExecutiveRoute
  AuthenticatedAdminRankingRoute: typeof AuthenticatedAdminRankingRoute
  AuthenticatedAdminTrashRoute: typeof AuthenticatedAdminTrashRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRouteWithChildren
  AuthenticatedTicketsNewRoute: typeof AuthenticatedTicketsNewRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedAdminTechniciansIdRoute: typeof AuthenticatedAdminTechniciansIdRoute
  AuthenticatedAdminTicketsIdRoute: typeof AuthenticatedAdminTicketsIdRoute
  AuthenticatedAdminTechniciansIndexRoute: typeof AuthenticatedAdminTechniciansIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminCompareRoute: AuthenticatedAdminCompareRoute,
  AuthenticatedAdminExecutiveRoute: AuthenticatedAdminExecutiveRoute,
  AuthenticatedAdminRankingRoute: AuthenticatedAdminRankingRoute,
  AuthenticatedAdminTrashRoute: AuthenticatedAdminTrashRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRouteWithChildren,
  AuthenticatedTicketsNewRoute: AuthenticatedTicketsNewRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedAdminTechniciansIdRoute: AuthenticatedAdminTechniciansIdRoute,
  AuthenticatedAdminTicketsIdRoute: AuthenticatedAdminTicketsIdRoute,
  AuthenticatedAdminTechniciansIndexRoute:
    AuthenticatedAdminTechniciansIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
